In [1]:
import numpy as np
import scipy.linalg

In [2]:
def vec(M):
    return np.reshape(M, [-1, 1])

def compute_A(M):
    n = M.shape[0]
    columns = [vec(np.eye(n))]
    for k in range(n):
        M_k = np.linalg.matrix_power(M, k+1)
        columns.append(vec(M_k))
    A = np.hstack(columns)
    return A

def annihilate_min_deg_poly(M):
    A = compute_A(M)
#     a = np.linalg.solve(A, np.zeros(A.shape[0]))
    a = np.linalg.lstsq(A, np.zeros(A.shape[0]), rcond=None)[0]
#     a = scipy.linalg.null_space(A).T[0]
#     a = np.poly(M)
    return a

def poly(a, M):
    p = 0
    for i in range(len(list(a))):
        p += a[i] * np.linalg.matrix_power(M, i)
    return p

M = np.array([[1, 3],
              [7, 4]])

A = compute_A(M)
r = np.linalg.matrix_rank(A)
a = annihilate_min_deg_poly(M)
p = poly(a, M)

print(f"M = {M}\n")
print(f"A = {A}\n")
print(f"r = {r}\n")
print(f"a = {a}\n")
print(f"p = {p}\n")

M = [[1 3]
 [7 4]]

A = [[ 1.  1. 22.]
 [ 0.  3. 15.]
 [ 0.  7. 35.]
 [ 1.  4. 37.]]

r = 2

a = [0. 0. 0.]

p = [[0. 0.]
 [0. 0.]]

